delete from USER;
insert into USER(id, firstName, lastName, email, administrator) values(1, 'John', 'DOE', 'jdoe@xebia.fr', FALSE);
insert into USER(id, firstName, lastName, email, administrator) values(2, 'Clement', 'LARDEUR', 'clardeur@xebia.fr', TRUE);
insert into USER(id, firstName, lastName, email, administrator) values(3, 'Yann', 'RENAUT', 'yrenaut@xebia.fr', TRUE);

delete from SLOT;
insert into SLOT (id, title, description, videoAccepted, scheduleDate, duration, author_id, slotType) values (1, 'JSF 2 en action', STRINGDECODE('Utilisation de JSF2 pour cr\u00E9er une web app, accompagn\u00E9e de PrettyFaces (Friendly Url, Navigation), OmniFaces (Utils) et PrimeFaces (Components)...\n\nUn socle de base sera fourni et il sera demand\u00E9 aux participants d''ajouter des fonctionnalit\u00E9s de mani\u00E8re progressive. Diff\u00E9rentes solutions seront propos\u00E9es concernant certaines probl\u00E9matiques.'), FALSE, DATE '2013-01-09', '2 h', 2, 5);
insert into SLOT (id, title, description, videoAccepted, scheduleDate, duration, author_id, slotType) values (2, 'Le web pour tous', STRINGDECODE('Ce slot sera l''occasion de de se sensibiliser \u00E0 la diff\u00E9rence des personnes handicap\u00E9es qui utilisent Internet, et un recueil de bonnes pratiques pour rendre le web accessible \u00E0 tous. D''abord nous verrons ensemble les diff\u00E9rents handicaps et l''outillage sp\u00E9cifique utilis\u00E9 pour naviguer sur le web. En SECOND lieu et \u00E0 travers plusieurs exercices, nous apprendrons \u00E0 coder des applications accessibles.'), FALSE, DATE '2013-01-09', '2 h', 1, 5);
insert into SLOT (id, title, description, videoAccepted, scheduleDate, duration, author_id, slotType) values (3, 'Scala for Beginners', STRINGDECODE('Vous entendez parler de Scala partout? Vous n''avez pas eu le temps de suivre les cours de Martin Odersky sur Coursera? Vous vouloir comment Scala peut vous permettre de faire du DDD SOLID ? Venez donc \u00E0 ce slot d\u00E9couvrir ce langage! En introduisant des r\u00E8gles fonctionnelles au fur et \u00E0 mesure de l''exercice, nous verrons comment le langage nous permet de r\u00E9pondre \u00E0 ces probl\u00E9matiques.'), FALSE, DATE '2013-01-09', '2 h', 1, 5);
insert into SLOT (id, title, description, videoAccepted, scheduleDate, duration, author_id, slotType) values (4, 'Monade pour les barbus', STRINGDECODE('Marre des sites qui se vantent de pr\u00E9senter les monades en pr\u00E9textant que c''est simple. Je vous propose enfin une session qui ose avouer tout haut ce que les autres pensent tout bas : les monades c''est compliqu\u00E9... ou pas ! Venez apprendre de nouveaux mots qui feront bien dans les soir\u00E9es parlantes. Venez vous faire d\u00E9coiffer par des lanc\u00E9s de burritos. Et si vous etes d\u00E9buttant, vous ne serez pas \u00E9pargn\u00E9s : du Java avec des generics \u00E0 rallonge, du Scala imbittable et plein d''autres langages aussi \u00E9sot\u00E9riques les uns que les autres. Avec en plus, la v\u00E9rit\u00E9 sur l''op\u00E8rateur elvis et le TYPE Optional de Guava et du JDK 8 : pourquoi C''est dr\u00F4le ? Dans cette SESSION, ON ne nourrit pas les trolls... ON les mange en direct !!! FLATMAP ZAT SHIT POWAA!!!'), FALSE, DATE '2013-03-09', '3 h', 1, 5);
insert into SLOT (id, title, description, videoAccepted, scheduleDate, duration, author_id, slotType) values (5, 'Le futur de javascript - Ecmascript 6', STRINGDECODE('Javascript est de plus en plus utilis\u00E9 pour tout et n''importe quoi, et montre de ce fait parfois des limites auquelles on ne s''attendait pas. Mais, pas de panique ! L''ECMA, association standardisant ECMAScript (dont javascript est un dialecte) travaille activement sur la prochaine version de son langage : ECMAScript 6 (nom de code : Harmony). Venez d\u00E9couvrir durant ce slot ce que nous r\u00E9serve ce langage, et \u00E9ventuellement ce qui est d\u00E9j\u00E0 pr\u00E9sent dans les navigateurs dignes de ce nom. ON parlera ici de classes, de varargs, de Map, de SET, et bien d''autres choses encore !'), FALSE, DATE '2013-03-09', '2 h', 1, 4);